### ISSUE TITLE
Feature Request: change 'ONGOING' and 'NEXT CLASS' automatically without reload

### ISSUE THREAD

**Issue by aspieln3r** [sumadithya/basic-time-table#8]
It'd be nice if the timetable automatically update those two fields without the user having to reload.

**Comment by starkizard** [comment]
the main.js file does all the stuff. it calculates the current time and figures out which slot the time lands in and thus the current and the next class. Is there some way to reload the script say every 5 minutes?

**Comment by aspieln3r** [comment]
no way to do something like 
```
while(1){
    print_table()
    sleep(5 mins)
}
```
in js?

**Comment by starkizard** [comment]
That could be done but as far as I know most browsers make webpages static to save RAM.
An auto refresh command could come in handy but it needs testing

**Comment by starkizard** [comment]
Tried something along these lines, works on my machine. merged the PR. Can you test for 2-3 days or so and close if this feature works fine for you now?

**Comment by aspieln3r** [comment]
lgtm

**Comment by rusty-tendrils** [comment]
Fixed by #9
